### PR TITLE
Added the discussed fix for the standard appender

### LINKED ISSUE #20: Custom log breaks in node context
I'm building an isomorphic application which executes the same code both on a node-server and in the browser.
When I manually call `Canadarm.warn('test')` in the "node-context" I get the following error:

```
project/node_modules/canadarm/build/canadarm.js:472
    var scripts = window.document.getElementsByTagName('script');
                                   ^

TypeError: window.document.getElementsByTagName is not a function
    at standardLogAppender (project/node_modules/canadarm/build/canadarm.js:472:35)
    at gatherErrors (project/node_modules/canadarm/build/canadarm.js:278:18)
    at Object.warn (project/node_modules/canadarm/build/canadarm.js:337:15)
    at Object.module.exports.Object.defineProperty.value (project/dist/server/index.js:1115:19)
    at __webpack_require__ (project/dist/server/index.js:508:30)
    at fn (project/dist/server/index.js:39:20)
    at Object.<anonymous> (project/dist/server/index.js:967:13)
    at __webpack_require__ (project/dist/server/index.js:508:30)
    at fn (project/dist/server/index.js:39:20)
    at Object.module.exports.Object.defineProperty.value (project/dist/server/index.js:926:14)
error: Forever detected script exited with code: 1
``` 

The code in Canadarm which does this is:

```
  // If stack is not defined we are in a browser that does not fully support our logging.
  // Or one of our custom loggers was called, e.g. Logger.debug('message').
  if (exception === undefined || exception === null || exception.stack === null) {
    var scripts = window.document.getElementsByTagName('script');
    scriptURL = (window.document.currentScript || scripts[scripts.length - 1]).src;

  }
```

Is Canadarm supposed to work with my kind of setup?

### PR DESCRIPTION
**Pull request by JohnPhoto**
This should fix #20
Please let me know if the coding "style" is not what you expected and I will update the fix.

### CODE REVIEW

File: lib/appender/standard.js [hunk 1]
```diff
@@ -111,8 +111,13 @@ function standardLogAppender(level, exception, message, data) {
   // If stack is not defined we are in a browser that does not fully support our logging.
   // Or one of our custom loggers was called, e.g. Logger.debug('message').
   if (exception === undefined || exception === null || exception.stack === null) {
-    var scripts = window.document.getElementsByTagName('script');
-    scriptURL = (window.document.currentScript || scripts[scripts.length - 1]).src;
+    if(typeof window.document.getElementsByTagName === 'function') {
```
Comment (gneatgeek) [inline lib/appender/standard.js]: Since `window` is undefined in a node context (unless someone defines it), would it be simpler to check if `window` is undefined?  

Per http://stackoverflow.com/questions/4224606/how-to-check-whether-a-script-is-running-under-node-js, it also looks like you can check for common support.

@garrypolley, do you have a preference?

-------

This is just a nitpick, but I'd like a space between the `if` and the opening paren.

**Comment by gneatgeek** [comment]
Thank you for contributing a fix for this!

When you have a chance, would you mind adding unit tests for this? https://github.com/cerner/canadarm/blob/1.0.1/test/unit/appender/standard.js

File: lib/appender/standard.js (hunk 1 above)
Comment (JohnPhoto) [inline lib/appender/standard.js]: Not possible due to the fact that window and window.document is mocked in the mock.js file

Comment (gneatgeek) [inline lib/appender/standard.js]: > Not possible due to the fact that window and window.document is mocked in the mock.js file

Ah yes, you're right, my bad.  I'm fine with it then :)

**Comment by JohnPhoto** [comment]
Added unit test for the fix, Also fixed the missing space after `if`

**Comment by gneatgeek** [comment]
:+1:

File: test/unit/appender/standard.js [hunk 2]
```diff
@@ -96,5 +96,19 @@ describe('Canadarm.Appender', function () {
         assert.equal(actualAttributes.scriptURL, 'fake-src');
       });
     });
+
+    describe('works without getElementsByTagName', function() {
```
Comment (gneatgeek) [inline test/unit/appender/standard.js]: Although this describe statement is accurate, I'd prefer it if it said something along the lines of "in a Node context" since that's the real problem we're making sure to fix.

**Comment by mhemesath** [comment]
Would a simpler approach be to just detect the global variable identifying the current file in Node and if not present fallback onto looking up the script? 

* https://nodejs.org/api/globals.html#globals_filename
* https://nodejs.org/api/globals.html#globals_dirname

**Comment by sambao21** [comment]
Could you please update the changelog and and contributors files as the CONTRIBUTING.md file?

**Comment by garrypolley** [comment]
I would prefer these approaches mentioned by Mike.

File: lib/appender/standard.js [hunk 3]
```diff
@@ -111,8 +111,13 @@ function standardLogAppender(level, exception, message, data) {
...
   // Or one of our custom loggers was called, e.g. Logger.debug('message').
   if (exception === undefined || exception === null || exception.stack === null) {
-    var scripts = window.document.getElementsByTagName('script');
-    scriptURL = (window.document.currentScript || scripts[scripts.length - 1]).src;
+    if (typeof window.document.getElementsByTagName === 'function') {
+      var scripts = window.document.getElementsByTagName('script');
+      scriptURL = (window.document.currentScript || scripts[scripts.length - 1]).src;
+    } else {
+      // Probably not in a browser, return unknown log.
+      scriptURL = Canadarm.constant.UNKNOWN_LOG;
```
Comment (garrypolley) [inline lib/appender/standard.js]: We know why this is not here, I'd rather not set the scriptURL at all because it does not make sense within the node context, unless we set it to the file path.

**Comment by JohnPhoto** [comment]
@mhemesath I do not 100% follow what you mean:

> Would a simpler approach be to just detect the global variable identifying the current file in Node and if not present fallback onto looking up the script?

**Comment by mhemesath** [comment]
The code exists to get the current file path. I'm simply suggesting that we check for the presence of the global variable that references the current file and path and use that. If those don't exist, then assume we are in a browser context and call getElementsByTagName

**Comment by JohnPhoto** [comment]
@mhemesath But usage of __filename in the standard-appender will always return the standard appender-filename, right? And anything else will alter the API of the logging, which I guess you don't want?

**Comment by mhemesath** [comment]
@JohnPhoto your right, duh :)

I was looking at the code though and it seems that [node errors](https://nodejs.org/api/errors.html#errors_class_error) have a stack property. How is the code even getting into this execution block in nodejs?  Admittedly I haven't done node programming in a while so there might be something I'm missing.

**Comment by JohnPhoto** [comment]
I agree with your assumption regarding exception and stack. But I put 
`console.log(typeof exception, exception);` at row 54 in the appender (directly after the first assignments in the appenderfunction. (row 413 in the build). 
There I got a `undefined, undefined` printout with my setup. 

My theory is that I'm doing a manual `Canadarm.warn('Test')` which maybe is not giving any exceptions, and therefore the code only crashes (prior to fix) with the manual logging and not when catching thrown errors.

**Comment by garrypolley** [comment]
> My theory is that I'm doing a manual Canadarm.warn('Test') which maybe is not giving any exceptions, and therefore the code only crashes (prior to fix) with the manual logging and not when catching thrown errors.

You are correct @JohnPhoto. Looking at the code it actually has this comment: 

> // Or one of our custom loggers was called, e.g. Logger.debug('message').

There is no exception passed and that's on purpose because there is not an exception. At the time of creation I don't think I fully understood the implications on node having that browser bit.

File: lib/appender/standard.js (hunk 3 above)
Comment (garrypolley) [inline lib/appender/standard.js]: I suppose this comment can/should be ignored.  :-)   It doesn't hurt to set it and it helps in searching if the scriptURL is a `?`.

**Comment by garrypolley** [comment]
I think this looks good. 👍  Thanks for the pull request.  I'll see if anyone has any objections and if not, I'll get this merged and published soon.
